In [ ]:
!pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import torch

In [ ]:
import numpy as np

In [ ]:
x = np.array([[1,2,3,4], [5,6,7,8]])

In [ ]:
x = torch.tensor(x)

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device("cuda:0")

In [ ]:
x_cuda = x.to(device)

In [ ]:
import torch

x = torch.tensor(
    [[1., 2., 3., 4.],
     [5., 6., 7., 8.],
     [9., 10., 11., 12.]], requires_grad = True)

############## если надо переложить на GPU:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
x = x.to(device)
##############

function = 10 * (x**2).sum()
x.retain_grad()
function.backward() # производная функции по тензору

print(x.grad, ' <- gradient')

x.data -= (0.001 * x.grad) # один градиентный шаг (0.001 - learning rate)
print(x.data)
x.grad.zero_() # ручное обнуление градиента после каждого шага (т.к. в PyTorch градиенты НАКАПЛИВАЮТСЯ)

tensor([[ 20.,  40.,  60.,  80.],
        [100., 120., 140., 160.],
        [180., 200., 220., 240.]], device='cuda:0')  <- gradient
tensor([[ 0.9800,  1.9600,  2.9400,  3.9200],
        [ 4.9000,  5.8800,  6.8600,  7.8400],
        [ 8.8200,  9.8000, 10.7800, 11.7600]], device='cuda:0')


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='cuda:0')

In [ ]:
x = torch.tensor([8., 8.], requires_grad=True)

optimizer = torch.optim.SGD([x], lr=0.001)

def function_parabola(variable):
  return 10 * (variable ** 2).sum()

def make_gradient_step(function, variable):
  function_result = function(variable)
  function_result.backward()
  optimizer.step() #градиентный шаг
  optimizer.zero_grad() # обнуление градиента

for i in range(500):
  make_gradient_step(function_parabola, x)

print(x.data)

tensor([0.0003, 0.0003])
